package lk.ac.uwu.cvi.enums;

public enum Characteristic {
    COLOR_PREFERENCE,
    ATTENTION_TO_LIGHT,
    ATTENTION_TO_MOVEMENT,
    VISUAL_LATENCY,
    PREFERRED_VISUAL_FIELD,
    VISUAL_COMPLEXITY,
    DIFFICULTY_IN_DISTANCE_VIEWING,
    ATYPICAL_VISUAL_REFLEXES,
    DIFFICULTY_IN_VISUAL_NOVELTY,
    ABSENCE_OF_VISUAL_GUIDED_REACH
}
